config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }
  match 'sign_up', to: 'remote_content#sign_up', via: [:get]
  match 'sign_in', to: 'remote_content#sign_in', via: [:get]
  # resources :users
  resources :projects, only: [:new, :create, :update, :destroy] do
  	post 'update_style'
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
 
end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user
  validates :name, presence: true
  validates :submission_date, presence: true
  validates :description, presence: true

  COLOR = ["red", "blue", "orange", "cyan"]

  FONT_SIZE = ["10", "15", "20", "25"]

  def project_picture
    image.nil? ? "no_image.png" : image.avatar.url
  end

  def creater
    user.name
  end

  def admin?(login_user)
    user == login_user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :company_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
  
  def profile_image
    avatar.url.nil? ? "avatar.png" : avatar.url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_project, only: [:edit, :update, :destroy]
  load_resource only: [:edit, :update, :destroy]
  # GET /projects
  # GET /projects.json
  

  # GET /projects/new
  def new
    @project = Project.new
    @project.build_image
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: 'Project was successfully created.'}
        format.js {}
      else
        @faild = true
        format.js { }
      end
    end
  end

  def update_style
    @project = Project.find(params[:project_id])
    @project.update(
      name_color: params[:name_color],
      name_font_size: params[:name_font_size],
      date_color: params[:date_color],
      date_font_size: params[:date_font_size],
      description_color: params[:description_color],
      description_text_color: params[:description_text_color]
    )

    respond_to do |format|
      format.js {}
    end
  end
  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :submission_date, :description, :user_id, :avatar)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def create
    build_resource(sign_up_params)
    if resource.save
      respond_to do |format|
        format.html {
          yield resource if block_given?
          if resource.active_for_authentication?
            set_flash_message :notice, :signed_up if is_flashing_format?
            sign_up(resource_name, resource)
            respond_with resource, :location => after_sign_up_path_for(resource)
          else
            set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
            expire_data_after_sign_in!
            respond_with resource, :location => after_inactive_sign_up_path_for(resource)
          end
        }
        format.js {
          flash[:notice] = "Signed up successfully."
          render :template => "remote_content/devise_success_sign_up.js.erb"
          flash.discard
          sign_up(resource_name, resource)
        }
      end
    else
      respond_to do |format|
        format.html {
          clean_up_passwords resource
          respond_with resource
        }
        format.js {
          flash[:alert] = @user.errors.full_messages.to_sentence
          render :template => "remote_content/devise_errors.js.erb"
          flash.discard
        }
      end
    end
  end

  protected
  # def after_update_path_for resource
  #   edit_user_registration_path
  # end

  # def after_sign_up_path_for(resource)
  #   root_path
  # end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :dob, :company_name, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :dob, :company_name, :avatar)
  end

  def update_resource(resource, params)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
      params.delete(:current_password)
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
end

app/controllers/remote_content_controller.rb
# coding: utf-8
class RemoteContentController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def create
    self.resource = warden.authenticate(auth_options)
    if resource && resource.active_for_authentication?
      sign_in(resource_name, resource)
      respond_to do |format|
        format.js {
          flash[:notice] = "Signed in successfully."
          render :template => "remote_content/devise_success_sign_up.js.erb"
          flash.discard
        }
      end
    else
      respond_to do |format|
        format.js {
          flash[:alert] = "Incorrect username or password"
          render :template => "remote_content/devise_errors.js.erb"
          flash.discard
        }
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	def index
		if current_user
      @user_projects = current_user.projects
      @project = Project.new
    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def flash_normal
    render "shared/flashes"
  end

  def flash_form
    render "shared/form_flashes"
  end

  def twitterized_type(type)
    case type
      when :errors
        "alert-error"
      when :alert
        "alert-warning"
      when :error
        "alert-error"
      when :notice
        "alert-success"
      else
        "alert-info"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%#= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to "Sign in", sign_in_path, :remote => true %></li>
  <li><%= link_to "Sign up", sign_up_path, :remote => true %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="user_name"><%= current_user.name %></li>
          <li class="image_nav"><%= image_tag(current_user.profile_image, class: "img-circle", width: "25px")%></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "OnePageApp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Solute demo" %>">
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <% unless current_user %>
      <div class="intro-header">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>  
      </div>
    <% else %>
      <main role="main">
        <div class="container">
          <div class="row">
            <%= render 'layouts/messages' %>
            <div class="container-fluid" style="padding-top: 20px;">
              <div class="row">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </main>
    <% end %>
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <p class="copyright small">Copyright &copy; Onepageapp 2016. All Rights Reserved</p>
            <ul>
              
            <ul>
          </div>
        </div>
      </div>
  </footer>

  </body>
</html>
<style type="text/css">
  
html,body{
    height: 100%
}
.footer {
  background-color: seagreen;
  padding-bottom: inherit;
  padding-top: 0;
} 
</style>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Solute Technolabs</h3>
<p>
Finest web development firm in ahhamdabd
</p>

app/views/projects/_form.html.erb
<div class="col-md-6 col-sm-8 col-xs-12 white_bg">
  <%= form_for project, :remote => true do |f| %>
    
    <div id="project_error"></div>
    
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, as: :wysihtml5,class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :submission_date %><br>
      <%= f.text_field :submission_date, class: 'form-control datepicker' %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'form-control'%>
    </div>
    <div class="actions">
      <%= f.submit 'Save', :class => 'btn btn-success' %>
    </div>
  <% end %>
    
</div>

app/views/projects/create.js.erb
<% if @faild %>
  $("#project_error").html("<%= escape_javascript render(:partial => 'shared/error_messages', :locals => {  :object =>  @project }) %>");
<% else %>
  window.location.reload();
  $("#project_error").html("");
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>
<%= render 'form' %>

app/views/projects/invite_user.js.erb
$("#myModal1").modal('toggle');
<% if flash[:notice] %>
    $(".alert").html("<%= escape_javascript flash[:notice]%>");
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<div class="container">
<style type="text/css">
  .dropdown-menu{
    position: absolute;
    z-index: 9999;
  }
</style>
  <!-- Portfolio Item Heading -->
  <div class="row">
    <div class="col-lg-12">
    <h1 class="page-header"><%= @project.name %>
        <small>created by <%= @project.creater%></small>
      </h1>
    </div>
  </div>
  <!-- /.row -->

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-6">
      <%= image_tag(@project.project_picture, class: "img-responsive")%>
    </div>

    <div class="col-md-4">
      <h3>Project Description</h3>
      <p><%= @project.description %></p>
      <h3>Project Submission date</h3>
      <p><%= @project.submission_date %></p>
      <% if @project.admin?(current_user)%>
        <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-info" %>
        <%= link_to 'delete', project_path(@project), method: :delete, class: "btn btn-danger" %>
        <!-- task Modal -->
    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">
      
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Add new task</h4>
          </div>
          <div class="modal-body">
            <%= form_for(@task, remote: true) do |f| %>
              <div class="task_error_message"></div>
              <%# binding.pry%>
              <%= f.hidden_field :project_id, value: @project.id%>
              <div class="form-group">
                <%= f.label :title %><br>
                <%= f.text_field :title, class: 'form-control', placeholder: "title"%>
              </div>
              <div class="form-group">
                <%= f.label :due_date %><br>
                <%= f.text_field :due_date, class: 'form-control datepicker', placeholder: "select date" %>
              </div>
              <div class="form-group">
                <%= f.label :description %><br>
                <%= f.text_area :description, class: 'form-control', placeholder: "description"%>
              </div>
              <%= f.submit "create", class: "btn btn-success"%>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
        
      </div>
    </div>
      <% end %>
    </div>

  </div>
  <!-- /.row -->
  <br>
  <% if @project.admin?(current_user)%>
    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal">+ Add task</button>
    <button type="button" class="btn btn-success fa fa-user fa-2x pull-right" data-toggle="modal" data-target="#myModal1">+ Invite</button>


    <!-- invite Modal -->
    <div id="myModal1" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Invite user</h4>
          </div>
          <div class="modal-body">
            <%= form_tag(invite_user_project_path(@project), method: "get", remote: true) do %>
              <div class="form-group">
                <%= select_tag(:invited_user_id, options_for_select(User.all.map{|e| [e.name, e.id] }), {id: "test", class: "form-control", prompt: "select"}) %>
                <%= submit_tag "invite", class: "btn btn-success"%>
              </div>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>
    </div>

  <% end %>
  <!-- Related Projects Row -->
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">Tasks</h3>
      <div id="tasks_table">
        <%= render :partial => 'tasks/tasks', :locals => {:project => @project} %>
      </div>
    </div>
  </div>
  <%= link_to 'Back', projects_path, class: "btn btn-primary pull-right"%>

  <hr>
</div>

<style type="text/css">
  .select2-container--open .select2-dropdown{
    margin-top: 20px;
  }
  .select2-container--default .select2-selection--single{
    border-radius: 0;
    height: 34px;
    width: 106px;
  }
</style>

app/views/projects/update_style.js.erb
$("#myModal-<%= @project.id%>").modal('toggle');
window.location.reload();

app/views/remote_content/_sign_in.html.erb
<div class="modal fade" id="signin" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Sign in</h4>
      </div>
      <div class="modal-body">
          <%= form_for(resource, 
              :as => resource_name,
              :remote => true,
              :url => session_path(resource_name), 
              :html => { :role => 'form'}) do |f| %>
            
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, :autofocus => true, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
              <%= f.submit 'Sign in', :class => 'btn btn-success' %>
              <% if devise_mapping.rememberable? -%>
                <div class="checkbox" style="width:150px">
                  <label>
                    <%= f.check_box :remember_me %> Remember me
                  </label>
                </div>
              <% end -%>
          <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/remote_content/_sign_up.html.erb
<div class="modal fade" id="signup" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Sign in</h4>
      </div>
      <div class="modal-body">
        <%= form_for(resource, 
              :as => resource_name, 
              :remote => true,
              :url => registration_path(resource_name), 
              :html => { :role => 'form'}) do |f| %>

          <div id="errors" style="display: none;"></div>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :company_name %>
            <%= f.text_field :company_name, class: 'form-control' %>
          </div>
          
          <div class="form-group select_image">
            <i class="fa fa-file-image-o fa-2x"></i>&nbsp;
            <label>Click to select profile image</label>
          </div>
          <div class="form-group">
            <%= f.file_field :avatar, class: "form-control", id: "imageable"%>
            <img id="blah" src="#" alt="your image"/>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
           <%= f.submit 'Sign up', :class => 'btn btn-success' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/remote_content/devise_errors.js.erb
if($('#flash').length > 0) {
  $('#flash').remove();
  $('.modal-body').prepend("<%= escape_javascript raw(flash_form) %>");
}
else {
  $('.modal-body').prepend("<%= escape_javascript raw(flash_form) %>");
}

app/views/remote_content/devise_success_sign_up.js.erb
$('.modal').modal('hide')
window.location.reload();
if($('#flash').length > 0) {
  $('#flash').remove();
  $('.intro-header').prepend("<%= escape_javascript raw(flash_normal) %>");
}
else {
  $('.modal').modal('hide')
  $('.intro-header').prepend("<%= escape_javascript raw(flash_normal) %>");
}

app/views/remote_content/sign_in.js.erb
if($('.modal').length > 0) {
  $("#signin").modal();
}
else {
  $("body").prepend("<%= escape_javascript(render 'remote_content/sign_in', :formats => [:html]) %>");
  $("#signin").modal();
}

app/views/remote_content/sign_up.js.erb
if($('.modal').length > 0) {
  $("#signup").modal();
}
else {
  $("body").prepend("<%= escape_javascript(render 'remote_content/sign_up', :formats => [:html]) %>");
  $("#signup").modal();
}

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<div id='flash'>
  <% flash.each do |type, message| %>
    <div class='alert alert-success'>
      <button aria-hidden='true' class='close' data-dismiss='alert'>×</button>
      <li><%= message %></li>
    </div>
  <% end %>
</div>

app/views/shared/_form_flashes.html.erb
<div id='form_flashes'>
  <% flash.each do |type, message| %>
    <div class='alert alert-danger'>
      <button aria-hidden='true' class='close' data-dismiss='alert'>×</button>
      <p><%= message %></p>
    </div>
  <% end %>
</div>

app/views/visitors/_logged_user_index.html.erb
<div class="row">
  <div class="col-lg-12">
    
      <div class="panel panel-info">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" href="#collapse1">Click to see all projects(<%= @user_projects.count%>)</a>
          </h4>
        </div>
        <div id="collapse1" class="panel-collapse collapse">
          <ul class="list-group">
            <% unless @user_projects.blank? %>
              <% @user_projects.each do |p|%>
                <li class="list-group-item">
                  <div style="color: <%= p.name_color %>; font-size: <%= p.name_font_size %>px;">Name: <%= p.name %></div><br>
                  <div style="color: <%= p.date_color %>; font-size: <%= p.date_font_size %>px;">Submittion_date: <%= p.submission_date %></div><br>
                  <div style="color: <%= p.description_color %>; font-size: <%= p.description_text_color %>px;">Description: <%= p.description %></div><br>
                  <div class="clearfix"></div><br>
                  <button type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#myModal-<%= p.id%>">customize</button>

                  <!-- Modal -->
                  <div class="modal fade" id="myModal-<%= p.id%>" role="dialog">
                    <div class="modal-dialog modal-sm">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">customize</h4>
                        </div>
                        <div class="modal-body">
                          <%= form_tag( project_update_style_path(p), remote: true) do  %>

                            <%= label_tag :name_color %>
                            <%= select_tag :name_color, options_for_select(Project::COLOR) %><br>

                            <%= label_tag :name_font_size %>
                            <%= select_tag :name_font_size, options_for_select(Project::FONT_SIZE) %><br>

                            <%= label_tag :date_color %>
                            <%= select_tag :date_color, options_for_select(Project::COLOR) %><br>

                            <%= label_tag :date_font_size %>
                            <%= select_tag :date_font_size, options_for_select(Project::FONT_SIZE) %><br>
                            

                            <%= label_tag :description_color %>
                            <%= select_tag :description_color, options_for_select(Project::COLOR) %><br>

                            <%= label_tag :description_text_color %>
                            <%= select_tag :description_text_color, options_for_select(Project::FONT_SIZE) %><br>
                            
                            <%= submit_tag "save", class: "btn btn-primary" %>
                          <% end %>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
              <% end %>
            <% else %>
              <p>No projects available.. ! </p>
            <% end %>
          </ul>
        </div>
      </div>
    <button type="button" class="btn btn-warning" data-toggle="collapse" data-target="#demo">
    Add project
    </button>
    <div class="clearfix"></div><br>
    <div id="demo" class="collapse">
      <div class="">
        <%= render partial: 'projects/form', locals: {project: @project} %>
      </div>
    </div>
  </div>
</div>

app/views/visitors/_unlogged_user_index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="intro-message">
      <h1>Single page application</h1>
      <hr class="intro-divider">
      <h3>Welcome, <%= user_signed_in? ? "#{current_user.name}" : "Guest" %></h3>
      <div class="col-md-12">
        <h4>Hi, this is demo application. </h4>
      </div>
      
      <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#signup">Sign up</button> OR <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#signin">Sign in</button>
    </div>
  </div>
</div>
<%= render 'remote_content/sign_in' %>
<%= render 'remote_content/sign_up' %>

app/views/visitors/index.html.erb
<% if user_signed_in? %>
  <%= render 'visitors/logged_user_index' %>
<% else %>
  <%= render 'visitors/unlogged_user_index' %>
<% end %>